# Generated by Django 5.2.4 on 2026-06-12 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='categories/genders/', verbose_name='آیکون')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'جنسیت',
                'verbose_name_plural': 'جنسیت\u200cها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Nature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='categories/natures/', verbose_name='آیکون')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'طبع',
                'verbose_name_plural': 'طبع\u200cها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='notes/', verbose_name='تصویر')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'نوت',
                'verbose_name_plural': 'نوت\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Scent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ')),
                ('color', models.CharField(default='#D4A574', help_text='رنگ نوار نمایشی', max_length=7, verbose_name='رنگ نمایشی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'رایحه',
                'verbose_name_plural': 'رایحه\u200cها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ScentFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ')),
                ('color', models.CharField(default='#6B4C9A', help_text='کد رنگ HEX مثل #6B4C9A', max_length=7, verbose_name='رنگ نمایشی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'گروه بویایی',
                'verbose_name_plural': 'گروه\u200cهای بویایی',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='categories/seasons/', verbose_name='آیکون')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'فصل',
                'verbose_name_plural': 'فصل\u200cها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Taste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='categories/tastes/', verbose_name='آیکون')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'طعم',
                'verbose_name_plural': 'طعم\u200cها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام عطر')),
                ('slug', models.SlugField(allow_unicode=True, max_length=250, unique=True, verbose_name='اسلاگ')),
                ('brand', models.CharField(max_length=200, verbose_name='برند')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='توضیح کوتاه')),
                ('longevity', models.CharField(choices=[('very_low', 'بسیار کم'), ('low', 'کم'), ('moderate', 'متوسط'), ('high', 'بالا'), ('very_high', 'بسیار بالا')], default='moderate', max_length=20, verbose_name='ماندگاری')),
                ('sillage', models.CharField(choices=[('intimate', 'ملایم'), ('moderate', 'متوسط'), ('strong', 'قوی'), ('enormous', 'قوی و نافذ')], default='moderate', max_length=20, verbose_name='پراکندگی')),
                ('gender_male_percent', models.PositiveIntegerField(default=50, help_text='درصد مناسب بودن برای آقایان', verbose_name='درصد مردانه')),
                ('gender_female_percent', models.PositiveIntegerField(default=50, help_text='درصد مناسب بودن برای خانم\u200cها', verbose_name='درصد زنانه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_featured', models.BooleanField(default=False, verbose_name='محصول ویژه')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfumes', to='products.gender', verbose_name='جنسیت')),
                ('nature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfumes', to='products.nature', verbose_name='طبع')),
            ],
            options={
                'verbose_name': 'عطر',
                'verbose_name_plural': 'عطرها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerfumeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='perfumes/%Y/%m/', verbose_name='تصویر')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='متن جایگزین')),
                ('is_primary', models.BooleanField(default=False, verbose_name='تصویر اصلی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.perfume', verbose_name='عطر')),
            ],
            options={
                'verbose_name': 'تصویر عطر',
                'verbose_name_plural': 'تصاویر عطر',
                'ordering': ['-is_primary', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PerfumeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('top', 'نوت آغازی'), ('middle', 'نوت میانی'), ('base', 'نوت پایانی')], max_length=10, verbose_name='دسته\u200cبندی نوت')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfume_notes', to='products.note', verbose_name='نوت')),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfume_notes', to='products.perfume', verbose_name='عطر')),
            ],
            options={
                'verbose_name': 'نوت عطر',
                'verbose_name_plural': 'نوت\u200cهای عطر',
                'ordering': ['category', 'order'],
                'unique_together': {('perfume', 'note', 'category')},
            },
        ),
        migrations.AddField(
            model_name='perfume',
            name='notes',
            field=models.ManyToManyField(blank=True, through='products.PerfumeNote', to='products.note', verbose_name='نوت\u200cها'),
        ),
        migrations.AddField(
            model_name='perfume',
            name='scents',
            field=models.ManyToManyField(blank=True, related_name='perfumes', to='products.scent', verbose_name='رایحه\u200cها'),
        ),
        migrations.AddField(
            model_name='perfume',
            name='scent_family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfumes', to='products.scentfamily', verbose_name='گروه بویایی'),
        ),
        migrations.AddField(
            model_name='perfume',
            name='seasons',
            field=models.ManyToManyField(blank=True, related_name='perfumes', to='products.season', verbose_name='فصل\u200cها'),
        ),
        migrations.AddField(
            model_name='perfume',
            name='tastes',
            field=models.ManyToManyField(blank=True, related_name='perfumes', to='products.taste', verbose_name='طعم\u200cها'),
        ),
        migrations.CreateModel(
            name='PerfumeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(choices=[(50, '۵۰ میلی\u200cلیتر'), (100, '۱۰۰ میلی\u200cلیتر')], verbose_name='حجم (میلی\u200cلیتر)')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت (تومان)')),
                ('discount_percent', models.PositiveIntegerField(default=0, help_text='عدد بین ۰ تا ۱۰۰', verbose_name='درصد تخفیف')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='کد محصول (SKU)')),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.perfume', verbose_name='عطر')),
            ],
            options={
                'verbose_name': 'واریانت عطر',
                'verbose_name_plural': 'واریانت\u200cهای عطر',
                'ordering': ['size'],
                'unique_together': {('perfume', 'size')},
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ افزودن')),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='products.perfume', verbose_name='عطر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'علاقه\u200cمندی',
                'verbose_name_plural': 'علاقه\u200cمندی\u200cها',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'perfume')},
            },
        ),
    ]
