# Generated by Django 5.2.4 on 2026-08-17 19:15

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_review_reviewlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='توضیحات'),
        ),
    ]
