# Generated by Django 5.2.4 on 2026-08-24 — PRODUCTION-SAFE
#
# Strategy (3 steps in one atomic transaction):
#   Step 1: Add new M2M field  scent_families  (keeps old scent_family_id intact)
#   Step 2: DATA migration — copy scent_family_id -> scent_families M2M rows
#   Step 3: Remove old FK column  scent_family
#
# This order guarantees zero data loss even if the migration is interrupted,
# because the data copy happens inside a transaction before the FK column is dropped.

from django.db import migrations, models


def copy_scent_family_to_m2m(apps, schema_editor):
    """
    انتقال داده‌های FK قدیمی (scent_family_id) به جدول M2M جدید (scent_families).
    از apps.get_model استفاده می‌شود تا با نسخه تاریخی مدل کار کنیم.
    """
    Perfume = apps.get_model('products', 'Perfume')
    db_alias = schema_editor.connection.alias

    # واکشی تمام عطرهایی که scent_family_id دارند
    # در این مرحله هنوز ستون scent_family_id در دیتابیس وجود دارد
    for perfume in Perfume.objects.using(db_alias).filter(scent_family_id__isnull=False):
        perfume.scent_families.add(perfume.scent_family_id)


def reverse_copy(apps, schema_editor):
    """
    Reverse: برگشت به حالت قبل — پاک کردن M2M (FK بعداً توسط Django بازسازی می‌شود)
    """
    Perfume = apps.get_model('products', 'Perfume')
    db_alias = schema_editor.connection.alias
    for perfume in Perfume.objects.using(db_alias).all():
        perfume.scent_families.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_perfume_description'),
    ]

    operations = [
        # ── Step 1: اضافه کردن فیلد M2M جدید (ستون FK قدیم هنوز سر جایش است) ──
        migrations.AddField(
            model_name='perfume',
            name='scent_families',
            field=models.ManyToManyField(
                blank=True,
                related_name='perfumes',
                to='products.scentfamily',
                verbose_name='گروه\u200cهای بویایی',
            ),
        ),

        # ── Step 2: کپی داده از FK قدیم به M2M جدید ──
        migrations.RunPython(copy_scent_family_to_m2m, reverse_code=reverse_copy),

        # ── Step 3: حذف ستون FK قدیم ──
        migrations.RemoveField(
            model_name='perfume',
            name='scent_family',
        ),
    ]
