# Generated by Django 5.2.4 on 2026-06-12 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد تخفیف')),
                ('discount_percent', models.PositiveIntegerField(help_text='عدد بین ۱ تا ۱۰۰', verbose_name='درصد تخفیف')),
                ('max_discount', models.PositiveIntegerField(blank=True, help_text='حداکثر مبلغ تخفیف قابل اعمال. خالی = بدون محدودیت', null=True, verbose_name='حداکثر مبلغ تخفیف (تومان)')),
                ('min_order_amount', models.PositiveIntegerField(default=0, verbose_name='حداقل مبلغ سفارش (تومان)')),
                ('usage_limit', models.PositiveIntegerField(default=1, verbose_name='محدودیت تعداد استفاده')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده شده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('valid_from', models.DateTimeField(verbose_name='معتبر از')),
                ('valid_to', models.DateTimeField(verbose_name='معتبر تا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='شماره سفارش')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام گیرنده')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره تماس')),
                ('province', models.CharField(max_length=100, verbose_name='استان')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('postal_code', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('total_price', models.PositiveIntegerField(verbose_name='مبلغ کل')),
                ('discount_amount', models.PositiveIntegerField(default=0, verbose_name='مبلغ تخفیف')),
                ('coupon_discount', models.PositiveIntegerField(default=0, verbose_name='تخفیف کد تخفیف')),
                ('shipping_cost', models.PositiveIntegerField(default=0, verbose_name='هزینه ارسال')),
                ('final_price', models.PositiveIntegerField(verbose_name='مبلغ نهایی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('processing', 'در حال پردازش'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل داده شده'), ('cancelled', 'لغو شده'), ('refunded', 'مرجوع شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('payment_authority', models.CharField(blank=True, max_length=50, verbose_name='کد Authority')),
                ('ref_id', models.CharField(blank=True, max_length=50, verbose_name='شماره پیگیری')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پرداخت')),
                ('tracking_code', models.CharField(blank=True, max_length=50, verbose_name='کد پیگیری پستی')),
                ('note', models.TextField(blank=True, verbose_name='یادداشت مشتری')),
                ('admin_note', models.TextField(blank=True, verbose_name='یادداشت ادمین')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.couponcode', verbose_name='کد تخفیف')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfume_name', models.CharField(max_length=200, verbose_name='نام عطر')),
                ('size', models.IntegerField(verbose_name='حجم (ml)')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت واحد')),
                ('discount_percent', models.PositiveIntegerField(default=0, verbose_name='درصد تخفیف')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='سفارش')),
                ('variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.perfumevariant', verbose_name='واریانت')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش',
            },
        ),
    ]
